### ISSUE TITLE
Cannot find PEM

### ISSUE THREAD

**Issue by R6Wouter** [SeBuDesign/Buckaroo-PHP#13]
I am not able to find a PEM file nor the option to create one in Buckaroo. Could someone help me?

Thanks in advance.

**Comment by svennis94** [comment]
This is where it is located in the Buckaroo Payment Plaza: 

Go to Configuration > Manage Certificates BPE 3.0 (Beheer certificaten 3.0)

Creating a BPE 3.0 certificate is easy. 
You can click Make Certificate and select Export key as: PEM and Purpose: SOAP Gateway. Check Active and click Make certificate.

**Comment by svennis94** [comment]
Let me know if you could find and create it!

**Comment by R6Wouter** [comment]
Thank you, I managed to find it!
